#!/usr/bin/env python3
"""Scan the working tree (and, in CI, git history) for personal data.

This project ingests right-to-know responses containing real home addresses, phone
numbers, loyalty card numbers and purchase histories. The single most likely way it
fails is by leaking one of those into a public repository. This scanner is the
backstop for that.

Usage:
    scan_pii.py                     scan tracked + untracked-but-not-ignored files
    scan_pii.py PATH [PATH ...]     scan specific paths (how pre-commit invokes it)
    scan_pii.py --history           scan commit messages and diffs of the whole history
    scan_pii.py --history RANGE     scan a revision range, e.g. origin/main..HEAD

Exits non-zero on any finding. Matched text is masked in the output: a scanner that
prints the PII it found into a public CI log has not helped anyone.

False positives are suppressed per line, with a reason:

    upc = "00010000080000"  # pii-scan: allow known placeholder UPC

The marker may sit on the offending line or the line directly above it, so formats
without comments (JSON, CSV) can still be annotated from the line before.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DENYLIST_PATH = REPO_ROOT / "tools" / "denylist.txt"
GENERATOR_NAME = "generate.py"

SUPPRESSION = re.compile(r"pii-scan:\s*allow\b(?P<reason>.*)")
HUNK_HEADER = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@")
# \x01 marks a commit boundary. Author and committer lines are deliberately
# omitted: a repo owner's own git email is not the leak this tool looks for.
LOG_FORMAT = "--format=%x01%H%n%B"

# Never scanned: binary by nature, or not ours.
SKIP_DIR_PARTS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", "dist", "build", "htmlcov",
}
SKIP_SUFFIXES = {
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".svg", ".pdf", ".zip",
    ".gz", ".tgz", ".woff", ".woff2", ".ttf", ".otf", ".eot", ".sqlite",
    ".sqlite3", ".db", ".lock",
}

# Email domains that cannot belong to a real person.
ALLOWED_EMAIL_DOMAINS = {
    "example.com", "example.org", "example.net", "localhost",
    # Machine identities that appear in commit trailers, not people's inboxes.
    "noreply.github.com", "users.noreply.github.com", "anthropic.com",
}
ALLOWED_EMAIL_SUFFIXES = (".invalid", ".example", ".test", ".localhost")

US_STATES = (
    "AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|"
    "MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC"
)
STREET_TYPES = (
    "St|Street|Ave|Avenue|Rd|Road|Blvd|Boulevard|Ln|Lane|Dr|Drive|Ct|Court|Way|Pl|"
    "Place|Ter|Terrace|Cir|Circle|Hwy|Highway|Pkwy|Parkway|Trl|Trail|Loop|Row|Walk|"
    "Mews|Crescent|Alley|Grove"
)


@dataclass(frozen=True)
class Finding:
    origin: str          # file path, or a commit identifier during a history scan
    line_no: int
    rule: str
    matched: str
    hint: str

    def render(self) -> str:
        return (
            f"{self.origin}:{self.line_no}: [{self.rule}] {mask(self.matched)}"
            f"\n    {self.hint}"
        )


@dataclass(frozen=True)
class Rule:
    name: str
    pattern: re.Pattern[str]
    hint: str
    # Returns True when a raw regex match is a real finding.
    accept: Callable[[re.Match[str]], bool] = lambda _m: True
    # When False, the rule is skipped inside committed fixture directories.
    applies_in_fixtures: bool = True
    applies_in_tests: bool = True
    # When False, the rule is skipped only in fixture directories that ship a
    # generator. Those files are regenerated byte-for-byte by `make fixtures-check`
    # in CI, which is a stronger guarantee than any regex here: a hand-placed real
    # report does not match the generator's deterministic output. Hand-written
    # fixtures, which have no such check, keep every rule.
    applies_in_generated_fixtures: bool = True


def mask(text: str) -> str:
    """Show enough to locate the hit, not enough to leak it."""
    text = text.strip()
    if len(text) <= 4:
        return "*" * len(text)
    return f"{text[:2]}{'*' * (len(text) - 4)}{text[-2:]}"


def luhn_ok(digits: str) -> bool:
    total, parity = 0, len(digits) % 2
    for i, ch in enumerate(digits):
        d = int(ch)
        if i % 2 == parity:
            d *= 2
            if d > 9:
                d -= 9
        total += d
    return total % 10 == 0


def _email_is_real(m: re.Match[str]) -> bool:
    domain = m.group("domain").lower()
    return not (
        domain in ALLOWED_EMAIL_DOMAINS or domain.endswith(ALLOWED_EMAIL_SUFFIXES)
    )


def _phone_is_real(m: re.Match[str]) -> bool:
    # 555 is the reserved-for-fiction exchange.
    return m.group("exchange") != "555"


def _card_is_real(m: re.Match[str]) -> bool:
    digits = re.sub(r"\D", "", m.group(0))
    return 13 <= len(digits) <= 19 and luhn_ok(digits)


RULES: tuple[Rule, ...] = (
    Rule(
        name="EMAIL",
        pattern=re.compile(
            r"\b[A-Za-z0-9._%+-]+@(?P<domain>[A-Za-z0-9.-]+\.[A-Za-z]{2,})\b"
        ),
        hint="Use an example.com / example.org address instead.",
        accept=_email_is_real,
    ),
    Rule(
        name="PHONE",
        pattern=re.compile(
            r"(?<!\d)(?:\+?1[-. ]?)?\(?\d{3}\)?[-. ](?P<exchange>\d{3})[-. ]\d{4}(?!\d)"
        ),
        hint="Fabricated numbers must use the reserved 555 exchange.",
        accept=_phone_is_real,
    ),
    Rule(
        name="STREET_ADDRESS",
        pattern=re.compile(
            rf"\b\d{{1,6}}\s+(?:[A-Z][A-Za-z.'-]*\s+){{0,3}}(?:{STREET_TYPES})\b\.?",
        ),
        hint="Fabricated addresses must not resolve to a real location.",
        applies_in_generated_fixtures=False,
    ),
    Rule(
        name="ZIP_WITH_STATE",
        pattern=re.compile(rf"\b(?:{US_STATES})\b[ ,]+\d{{5}}(?:-\d{{4}})?\b"),
        hint="A state abbreviation next to a ZIP is an address fragment.",
        applies_in_generated_fixtures=False,
    ),
    Rule(
        name="ZIP_PLUS_FOUR",
        pattern=re.compile(r"(?<!\d)\d{5}-\d{4}(?!\d)"),
        hint="ZIP+4 identifies a household on its own.",
        applies_in_generated_fixtures=False,
    ),
    Rule(
        name="PAYMENT_CARD",
        pattern=re.compile(r"(?<!\d)(?:\d[ -]?){12,18}\d(?!\d)"),
        hint="Digit run passes a Luhn check; treat it as a card number.",
        accept=_card_is_real,
    ),
    Rule(
        name="SSN",
        pattern=re.compile(r"(?<!\d)(?!000|666|9\d\d)\d{3}-(?!00)\d{2}-(?!0000)\d{4}(?!\d)"),
        hint="Never store or fabricate SSN-shaped values.",
    ),
    Rule(
        name="LOYALTY_NUMBER",
        pattern=re.compile(r"(?<![\d.])\d{12,14}(?![\d.])"),
        hint="Loyalty-card-length digit run. Move it into a fixture, or suppress "
             "it inline if it is a UPC or other non-identifying code.",
        applies_in_fixtures=False,
    ),
    Rule(
        name="UUID",
        pattern=re.compile(
            r"\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
            r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b"
        ),
        hint="Report and request identifiers are pseudonymous, not anonymous.",
        applies_in_fixtures=False,
        applies_in_tests=False,
    ),
)


def load_denylist() -> tuple[str, ...]:
    """Literal strings that must never appear. The file is itself gitignored."""
    if not DENYLIST_PATH.exists():
        return ()
    entries = []
    for raw in DENYLIST_PATH.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            entries.append(line.lower())
    return tuple(entries)


def classify(path: str) -> tuple[bool, bool]:
    """Return (is_fixture, is_test) for a repo-relative path."""
    p = Path(path)
    is_fixture = "fixtures" in p.parts
    is_test = p.parts[:1] == ("tests",) or p.name.startswith("test_")
    return is_fixture, is_test


def is_generated_fixture(path: str) -> bool:
    """True for a fixture that sits beside a generator that reproduces it.

    A report facsimile has to contain address-shaped data to be structurally
    faithful, so a few rules stand down here. What replaces them is stronger:
    `make fixtures-check` regenerates these files from a fixed seed and fails on
    any difference, so a real report dropped into the directory is caught by not
    matching what the generator produces.
    """
    p = Path(path)
    if "fixtures" not in p.parts:
        return False
    return (REPO_ROOT / p.parent / GENERATOR_NAME).is_file()


def suppressed(line: str, preceding: str = "") -> bool:
    """A marker on this line, or the line directly above it, silences findings here.

    A bare marker does not suppress: a reason is required, so that skipping a rule
    is always a decision somebody wrote down.
    """
    for candidate in (line, preceding):
        m = SUPPRESSION.search(candidate)
        if m and m.group("reason").strip():
            return True
    return False


def scan_lines(
    lines: Sequence[str],
    origin: str,
    *,
    is_fixture: bool = False,
    is_test: bool = False,
    is_generated_fixture: bool = False,
    denylist: Sequence[str] = (),
    line_offset: int = 1,
    preceding: str = "",
) -> list[Finding]:
    """Scan `lines`. `preceding` is the line above lines[0], supplied when the caller
    holds only a window into a larger file — the history walker sees one line at a
    time, and would otherwise miss every previous-line suppression."""
    active = [
        r for r in RULES
        if (r.applies_in_fixtures or not is_fixture)
        and (r.applies_in_tests or not is_test)
        and (r.applies_in_generated_fixtures or not is_generated_fixture)
    ]
    found: list[Finding] = []
    for idx, line in enumerate(lines):
        if suppressed(line, lines[idx - 1] if idx > 0 else preceding):
            continue
        lowered = line.lower()
        for needle in denylist:
            if needle in lowered:
                found.append(Finding(origin, idx + line_offset, "DENYLIST", needle,
                                     "Literal string from tools/denylist.txt."))
        for rule in active:
            for m in rule.pattern.finditer(line):
                if rule.accept(m):
                    found.append(
                        Finding(origin, idx + line_offset, rule.name, m.group(0), rule.hint)
                    )
    return found


def is_scannable(path: Path) -> bool:
    if any(part in SKIP_DIR_PARTS for part in path.parts):
        return False
    if path.suffix.lower() in SKIP_SUFFIXES:
        return False
    if not path.is_file():
        return False
    try:
        with path.open("rb") as fh:
            if b"\x00" in fh.read(8192):
                return False
    except OSError:
        return False
    return True


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT, check=True,
        capture_output=True, text=True,
    ).stdout


def tracked_and_untracked() -> list[str]:
    """Everything git would consider part of the repo. Ignored paths — data/ above
    all — are excluded by construction: this tool never reads the user's reports."""
    listed = git("ls-files", "--cached", "--others", "--exclude-standard").splitlines()
    return sorted(set(p for p in listed if p))


def scan_paths(paths: Iterable[str], denylist: Sequence[str]) -> list[Finding]:
    findings: list[Finding] = []
    for rel in paths:
        path = (REPO_ROOT / rel).resolve()
        if not is_scannable(path):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        is_fixture, is_test = classify(rel)
        findings.extend(
            scan_lines(text.splitlines(), rel, is_fixture=is_fixture, is_test=is_test,
                       is_generated_fixture=is_generated_fixture(rel), denylist=denylist)
        )
    return findings


def scan_history(rev_range: str | None, denylist: Sequence[str]) -> list[Finding]:
    """Scan commit messages and added lines across history.

    A contributor who commits their real report and then amends it away still gets
    caught here, before merge. Only added lines are scanned — context lines are
    already covered by the working-tree scan, and reporting them once per touching
    commit would bury the real finding. Author and committer identity lines are
    excluded by the --format: a repo owner's own git email is not the leak this tool
    is looking for.
    """
    args = ["log", "-p", "--no-color", "--no-merges", LOG_FORMAT]
    if rev_range:
        args.append(rev_range)
    try:
        out = git(*args)
    except subprocess.CalledProcessError as exc:
        print(f"scan_pii: could not read history ({exc.stderr.strip()})", file=sys.stderr)
        return []
    return scan_diff_stream(out, denylist)


def scan_diff_stream(out: str, denylist: Sequence[str] = ()) -> list[Finding]:
    """Walk `git log -p` output produced with LOG_FORMAT. Split out from
    scan_history so the diff walking is testable without a fixture repository."""
    findings: list[Finding] = []
    commit = "HEAD"
    current_file = ""
    in_message = False
    lineno = 0        # line number within the post-image of current_file
    msg_lineno = 0    # line number within the commit message
    prev_line = ""    # previous post-image line, so previous-line suppressions work
    prev_msg = ""

    for line in out.splitlines():
        if line.startswith("\x01"):
            commit, current_file, msg_lineno = line[1:][:12], "", 0
            in_message, prev_msg = True, ""
            continue
        if line.startswith("diff --git"):
            # A deletion diff names no post-image file, so current_file stays empty
            # and its body is skipped: that content was already scanned in the commit
            # that added it, and attributing it here would double-report.
            current_file, in_message, prev_line = "", False, ""
            continue
        if line.startswith("+++ b/"):
            current_file, prev_line = line[6:], ""
            continue
        if line.startswith("@@"):
            m = HUNK_HEADER.match(line)
            lineno = int(m.group(1)) if m else 0
            continue
        if line.startswith(("--- ", "index ", "old mode", "new mode", "similarity ",
                            "rename ", "new file", "deleted file", "Binary files")):
            continue

        if in_message:
            msg_lineno += 1
            findings.extend(scan_lines([line], f"{commit}:<message>", denylist=denylist,
                                       line_offset=msg_lineno, preceding=prev_msg))
            prev_msg = line
            continue
        if not current_file:
            continue

        if line.startswith("-"):
            continue          # removed line: it is not in the post-image
        if line.startswith("+"):
            content, at = line[1:], lineno
            lineno += 1
        elif line.startswith(" ") or line == "":
            # Context: already covered by the working-tree scan, but it still has to
            # be remembered, because a suppression may sit on an unchanged line.
            prev_line = line[1:] if line else ""
            lineno += 1
            continue
        else:
            continue

        is_fixture, is_test = classify(current_file)
        findings.extend(
            scan_lines([content], f"{commit}:{current_file}", is_fixture=is_fixture,
                       is_test=is_test,
                       is_generated_fixture=is_generated_fixture(current_file),
                       denylist=denylist, line_offset=at, preceding=prev_line)
        )
        prev_line = content
    return findings


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("paths", nargs="*", help="specific paths to scan")
    parser.add_argument(
        "--history", nargs="?", const="", default=None, metavar="RANGE",
        help="scan commit messages and diffs, optionally limited to a revision range",
    )
    args = parser.parse_args(argv)

    denylist = load_denylist()
    if args.history is not None:
        findings = scan_history(args.history or None, denylist)
        target = f"history {args.history}" if args.history else "full history"
    else:
        paths = args.paths or tracked_and_untracked()
        findings = scan_paths(paths, denylist)
        target = f"{len(paths)} path(s)"

    if not findings:
        note = "" if denylist else "  (no tools/denylist.txt — see CONTRIBUTING.md)"
        print(f"scan_pii: clean — {target}{note}")
        return 0

    print(f"scan_pii: {len(findings)} finding(s) in {target}\n", file=sys.stderr)
    for f in findings:
        print(f.render(), file=sys.stderr)
    print(
        "\nMatches are masked above. If a finding is genuinely benign, add"
        "\n  # pii-scan: allow <reason>"
        "\non the offending line or the line directly above it. Never bypass this"
        "\ncheck with --no-verify.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
